on:
  push:
    branches:
      - main

jobs:
  run-test:
    runs-on: ubuntu-latest
    name: Input name for the job
    steps:
      - uses: actions/checkout@v3
      - uses: kobiton/execute-appium-test-github-action@main
        with:
          kobi_username: ${{ secrets.KOBI_USERNAME }}
          kobi_api_key: ${{ secrets.KOBI_API_KEY }}
          executor_url: https://executor-demo.kobiton.com
          executor_username: ${{ secrets.EXECUTOR_USERNAME }} 
          executor_password: ${{ secrets.EXECUTOR_PASSWORD }} 
          git_repo_url: https://github.com/sonhmle/azure-devops-sample-java-prod.git
          git_repo_branch: master
          app_id: kobiton-store:568624
          use_custom_device: 'true'
          device_name: 'Galaxy *'
          device_platform_version: '12'
          device_platform: 'Android'
          root_directory: '/'
          command: 'mvn test'
          wait_for_execution: 'true'
